### ISSUE TITLE
Links on page with fill not rendered by optimize

### ISSUE THREAD

**Issue by McSinyx** [tlienart/Franklin.jl#797]
This is a bit obscure: there's [a page on my site](https://cnx.srht.site/blog/gsoc2020/) where links are not rendered:

![2021-03-11T22:34:24](https://user-images.githubusercontent.com/13689192/110812121-f1124880-82b9-11eb-9d0d-5bc78a03922b.png)

Upon some investigations, I noticed that [these lines](https://git.sr.ht/~cnx/site/tree/fc15c6a3/item/blog/gsoc2020/index.md?view-source#L134-147) are those causing the trouble:

    * [{{fill title ...}}](...)
    * ...

I also noticed that replace the unrendered links with the inline variant also solve the issue.

The issue occurs to me on both [0.10.30](https://builds.sr.ht/~cnx/job/454203) and the latest 0.10.33.

**Comment by tlienart** [comment]
Thanks for reporting!

Ok yes so that's a bit tricky in terms of the order in which things are resolved. Basically `{{...}}` blocks are currently left "untouched" and passed to the HTML processor so the ordering is:

1. markdown pass, most things are converted to HTML using MD -> HTML
2. html pass, remaining `{{...}}` items are resolved

So in this case there's a conflict because it sees "shortcut links" (like `[internship]()`) but it can't find the definition because the `{{...}}` is not yet resolved (at least I think that's what's happening for you, I haven't yet looked at your repo).

An alternative which would work now and might suit you is to define page variables with the links and fill those so something like

```
+++
benchmark = "/foo/bar/benchmark/"
+++

Did you [see the benchmarks]({{benchmark}}) etc.
```

The difference here is that the MD pass will lead to `<a href={{benchmark}}>see the benchmarks</a>` and the second pass will then appropriately fill so you'll get `<a href=/foo/bar/benchmark/>see the benchmarks</a>`.

**Comment by McSinyx** [comment]
Thanks, the suggested work-around indeed has the expected effect (the date is still incorrect though).  I also forgot to mention that running `serve` also fix it (even the date), which agrees with your analogy, but it feels too hacky for automation :smile:

**Comment by tlienart** [comment]
What is the date issue?

**Comment by McSinyx** [comment]
Affected pages also have the last modified date rendered as 0001-01-01.
My guess would be it's has the same root cause.

**Comment by tlienart** [comment]
Hmm no that's another issue which I'm aware of but haven't fixed yet. Thanks for reporting!

Just for the specific issue here, is the workaround suggested above ok for you? 

Note also that I'm working on a pretty significant refactoring of this (MD->HTML->HTML) pass which will likely remove the problem completely but I'm not sure exactly when I'll be done with it (it might take me a month or two).

Thanks again for the report!

**Comment by tlienart** [comment]
Ah could you try one thing for me please? Could you modify your `page foot` in the _layout and replace

`{{ fill fd_mtime }}` by `{{ fill fd_mtime fd_rpath}}`

this might not do anything useful but I'm just curious. Thanks!

**Comment by McSinyx** [comment]
Yes, the workaround is OK for me.  I'm looking forward to the refactored logic, although there's no hurry on my side.

**Comment by tlienart** [comment]
me too :joy:

**Comment by McSinyx** [comment]
I was able to [work around the date issue with `git log`](https://git.sr.ht/~cnx/site/commit/789398fa#utils.jl-1-4), which is a win-win since the modification date is not preserved by `git clone`.

**Comment by tlienart** [comment]
ah awesome! thanks for letting me know :)
